###############################################################
#  Generated by:      Cadence Innovus 22.18-s118_1
#  OS:                Linux x86_64(Host ID uvti_training)
#  Generated on:      Fri Aug  7 14:42:12 2026
#  Design:            darkbridge
#  Command:           saveDesign vlsithon3_testcase0.inn -tgz
###############################################################
current_design darkbridge
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {CLK}]  -name CLK -period 4.800000 -waveform {0.000000 2.400000}
set_propagated_clock  [get_clocks {CLK}]
set_propagated_clock  [get_ports {CLK}]
#END OF CLOCK SECTION#
set_wire_load_mode enclosed
